CREATE SEQUENCE suppliers_supplierid_seq OWNED BY suppliers.supplierid;
CREATE SEQUENCE shippers_shipperid_seq OWNED BY shippers.shipperid;
CREATE SEQUENCE region_regionid_seq OWNED BY region.regionid;
CREATE SEQUENCE categories_categoryid_seq OWNED BY categories.categoryid;
CREATE SEQUENCE employees_employeeid_seq OWNED BY employees.employeeid;
CREATE SEQUENCE orders_orderid_seq OWNED BY orders.orderid;
CREATE SEQUENCE products_productid_seq OWNED BY products.productid;
SELECT setval('suppliers_supplierid_seq',max(suppliers.supplierid) + 1) FROM suppliers;
SELECT setval('shippers_shipperid_seq',max(shippers.shipperid) + 1) FROM shippers;
SELECT setval('region_regionid_seq',max(region.regionid) + 1) FROM region;
SELECT setval('categories_categoryid_seq',max(categories.categoryid) + 1) FROM categories;
SELECT setval('employees_employeeid_seq',max(employees.employeeid) + 1) FROM employees;
SELECT setval('orders_orderid_seq',max(orders.orderid) + 1) FROM orders;
SELECT setval('products_productid_seq',max(products.productid) + 1) FROM products;
ALTER TABLE suppliers ALTER COLUMN supplierid SET DEFAULT nextval('suppliers_supplierid_seq');
ALTER TABLE shippers ALTER COLUMN shipperid SET DEFAULT nextval('shippers_shipperid_seq');
ALTER TABLE region ALTER COLUMN regionid SET DEFAULT nextval('region_regionid_seq');
ALTER TABLE categories ALTER COLUMN categoryid SET DEFAULT nextval('categories_categoryid_seq');
ALTER TABLE employees ALTER COLUMN employeeid SET DEFAULT nextval('employees_employeeid_seq');
ALTER TABLE orders ALTER COLUMN orderid SET DEFAULT nextval('orders_orderid_seq');
ALTER TABLE products ALTER COLUMN productid SET DEFAULT nextval('products_productid_seq');
